
/* ==========================================================================================
 * SteamshipMarkdownStream
 *
 * A SteamshipMarkdownStream emits Markdown containing text, images, audio, and video
 * generated by an LLM or Multimodal Agent.
 *
 * Since Steamship's native data model is to respond to completion requests with a "stream of
 * multi-modal streams", the SteamshipMarkdownStream wrapper funnels these into a single
 * text-only stream using Markdown to represent media.
 *
 * Video and Audio are embedded as links since Markdown lacks native support for these types.
 *
 * =========================================================================================*/

export function SteamshipMarkdownStream(
    reader: Response,
    callbacks?: AIStreamCallbacksAndOptions
): ReadableStream {
    return createParser(reader)
        .pipeThrough(createCallbacksTransformer(callbacks))
        .pipeThrough(
            createStreamDataTransformer(callbacks?.experimental_streamData)
        )
}